
# Copyright 2018 The GraphicsFuzz Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: generic

# First matrix entry builds graphicsfuzz repo and GLES workers.
# Second matrix entry builds vulkan-worker.

# The matrix entries install different versions of the Android SDK (for now).

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - INSTALL_SCRIPT="build/travis/1-install-deps-travis.sh"
        - BUILD_SCRIPT="python3.6 build/travis/build.py"
        - RELEASE_SCRIPT="python3.6 build/travis/release.py"
    - os: linux
      dist: trusty
      sudo: required
      env:
        - INSTALL_SCRIPT="build/ci_vulkan_worker/1-install-deps-travis.sh"
        - BUILD_SCRIPT="build/ci_vulkan_worker/2-build-travis.sh"
        - RELEASE_SCRIPT="python3.6 build/travis/release.py"
        - ANDROID_NDK_HOME=/data/android-sdk/ndk-bundle


install:
  - export ANDROID_HOME=/opt/android-sdk
  - export PATH="${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:/data/bin:$PATH"
  - $INSTALL_SCRIPT

script:
  - $BUILD_SCRIPT

after_success:
  - $RELEASE_SCRIPT
